<h1 align='center'>Numpy - многомерные массивы данных</h1>

[Cсылка](https://disk.yandex.ru/d/IE8K3D5e7q4fEw) на файлы лабораторной

In [3]:
# комменарий
%matplotlib inline 
#команда об интерактивном использовании matplotlib
import matplotlib.pyplot as plt #импорт функций подмодуля pyplot об интерактивном 
#использовании matplotlib

## Введение

Пакет `numpy` (модуль) используется почти во всех численных вычислениях с использованием Python. Это пакет, который обеспечивает высокопроизводительные векторные, матричные и многомерные структуры данных для Python. Он реализован на C и Fortran, поэтому, когда вычисления векторизуются (формулируются векторами и матрицами), производительность очень хорошая.
Чтобы использовать `numpy`, вам нужно импортировать модуль, используя, например,:

In [4]:
from numpy import * #при этом отсутсвует необходимость использования numpy.array
#import nympy as np - позволяет сократить имя объекта используя np.array

В пакете `numpy` терминологией, используемой для векторов, матриц и многомерных наборов данных, является *array*.


## Создание `numpy` *arrays*

Существует несколько способов инициализации новых массивов numpy, например из

* список Python или кортежи
* использование функций, предназначенных для генерации массивов numpy, таких как `arange`, `linspace` и т. д.
* чтение данных из файлов

### Создание из списка (*list*)

Например, для создания новых векторных и матричных массивов из списков Python мы можем использовать `numpy.array`.

In [5]:
# вектор: аргумент функции array список (list) Python
v = array([1,2,3,4])

v

array([1, 2, 3, 4])

In [6]:
# матрица: аргумент функции array вложенный список (nestled list) Python
M = array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

 `v` и `M` -- объекты общего типа `ndarray`, который создает модуль `numpy`.

In [7]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

Разница между `v` и `M` заключается только в их форме. Мы можем получить информацию о форме массива с помощью `ndarray.shape` свойства.

In [8]:
v.shape

(4,)

In [9]:
M.shape

(2, 2)

Количество элементов в массиве доступно через свойство `ndarray.size`:

In [10]:
M.size

4

Так же можно использовать функции `numpy.shape` и `numpy.size`. Использование дублирующих методы функций характерно для Python как языка поддерживающего как объектно-ориентированную так и функциональную парадигмы программирования.

In [11]:
shape(M)

(2, 2)

In [12]:
size(M)

4

До сих пор `numpy.ndarray` ужасно похож на список Python (или вложенный список). Почему бы просто не использовать списки Python для вычислений вместо создания нового типа массива?

Есть несколько причин:

* Списки Python очень общие. Они могут содержать любой вид объекта. Они динамически типизируются. Они не поддерживают математические функции, такие как матричное и точечное умножение и т. д. Реализация таких функций для списков Python была бы не очень эффективной из-за динамической типизации.
* Массивы Numpy **статически типизированы** и **однородны**. Тип элементов определяется при создании массива.
* Массивы Numpy эффективны для работы с памятью.
* Из-за статической типизации быстро реализуются математические функции, такие как умножение и сложение массивов `numpy`, функции могут быть реализованы на компилируемом языке (используется C и Fortran).

Используя свойство `dtype` (тип данных) `ndarray`, мы можем увидеть, какой тип имеют данные массива:

In [13]:
M.dtype

dtype('int64')

Обратите внимание, что при не совпадении типов при присвоении будет выдана ошибка, что есть следствие статической типизации `ndarray`:

In [14]:
M[0,0] = "hello"

ValueError: ignored

Если мы хотим, мы можем явно определить тип данных массива при его создании, используя аргумент ключевого слова `dtype`:

In [16]:
M = array([[1, 2], [3, 4]], dtype=complex)

M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Общие типы данных, которые можно использовать с `dtype`: `int`, `float`, `complex`, `bool`, `object` и т. д.

Мы также можем явно определить битовый размер типов данных, например: `int64`, `int16`, `float128`, `complex128`.

### Задание 1
Создайте матрицу таблицы умножения с использованием списков

In [17]:
matr = reshape(linspace(1, 10, 10, dtype = int), (1, 10))
matr1 = reshape(matr, (10, 1))

umnoz = matr1 @ matr
umnoz

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### Функции генерирующие массивы.

Для больших массивов нецелесообразно инициализировать данные вручную, используя явные списки Python. Вместо этого мы можем использовать одну из многих функций в `numpy`, которые генерируют массивы различных форм. Некоторые из наиболее распространенных являются:

#### Функция arange

In [ ]:
# массив целых от 0 до 10

x = arange(10, 5, -1) # аргументы: начало, конец, шаг
x

In [ ]:
x = arange(-1, 1, 0.1)

x

#### Функции linspace и logspace

In [ ]:
# использование linspace, оба конечных значения включены
linspace(5, 10, 11)

In [ ]:
logspace(0, 10, 11, base=10) # создание равномерной последовальности в логарифмической шкале

#### Функция mgrid

In [ ]:
x, y = mgrid[0:5, 0:5] #создает сетку равномерно расположенных значений подобно meshgrid в MATLAB

In [ ]:
x

In [ ]:
y

#### Создание случайных данных средствами random

In [ ]:
from numpy import random

In [ ]:
# случайные данные с равномерным распределением в отрезке [0,1]
random.rand(5,5)

In [ ]:
# случайные данные с нормальным распределением
random.randn(5,5)

#### Создание квадратных матриц функцией diag

In [ ]:
# матрица с диагональю
diag([1,2,3])

In [ ]:
# матрица со сдвинутой диагональю
diag([1,2,3], k=1) 

#### Матрицы или спецмассивы zeros и ones

In [ ]:
zeros((3,3))

In [ ]:
ones((3,3))

### Задание 2
Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии. 

In [ ]:
def create_matrix(n, el, dif):
  cons = arange(el, el + dif * n, dif)
  matr = diag(cons)
  return matr

create_matrix(10, 2, 5)

## Запись и чтение в файл

### Файлы данных Comma-separated values (CSV)

Очень распространенным форматом файлов данных являются значения, разделенные запятыми (CSV), или связанные с ними форматы, такие как TSV (значения, разделенные табуляциями). Для чтения данных из таких файлов в массивы Numpy мы можем использовать функцию `numpy.genfromtxt`. Например:

In [ ]:
data = genfromtxt('/content/sample_data/stockholm_td_adj.dat', dtype = float32)

In [ ]:
data.shape

In [ ]:
fig, ax = plt.subplots(figsize=(14,4))
x=linspace(1,32,31)
y=array([data[i,5] for i in range(data.shape[0]) if (data[i,0]==1950)*(data[i,1]==5)])
ax.plot(x,y)
ax.axis('tight')
ax.set_title('tempeatures in Stockholm')
ax.set_xlabel('year')
ax.set_ylabel('temperature (C)');


Используя `numpy.savetxt` можно записать Numpy массив в файл CSV формате:

In [ ]:
M = random.rand(3,3)

M

In [ ]:
savetxt("random-matrix.csv", M)

In [ ]:
savetxt("random-matrix.csv", M, fmt='%.5f') # fmt определяет формат данных
rand_data = genfromtxt('random-matrix.csv')
rand_data

### Формат файлов Numpy

Полезно при хранении и считывании данных массива numpy. Используйте функции `numpy.save` и `numpy.load`:

In [ ]:
save("random-matrix.npy", M)

In [ ]:
load("random-matrix.npy")

### Задание 3
Из данных по температуре в Стокгольме выбрать данные относящиеся к октябрю 1970 года и записать их в бинарный и текстовый файлы oct70.bin и oct70.txt. Затем прочитайте их импортировав в тетрадь ноутбука и сравните.

In [ ]:
cut1 = data[data[:, 0] == 1970]
cut2 = cut1[cut1[:, 1] == 10]

print(shape(cut2))

#savetxt("oct70.txt", cut2)
cut2.tofile("oct70.bin")
cut2.tofile("oct70.txt")

In [ ]:
?fromfile

In [ ]:
fromfile("oct70.bin")

In [ ]:
fromfile('oct70.txt')

## Дополнительные свойства `numpy` *arrays*

In [ ]:
M.itemsize # размер элемента в байтах

In [ ]:
M.nbytes # кол-во байт

In [ ]:
M.ndim # размерность

## Преобразование массивов

### Использование индексов

Доступ к элементам через индекс:

In [ ]:
# v -- вектор, размерность 1, испльзуем 1 индекс
v[0]

In [ ]:
# M -- матрица, 2-х мерный объект, используем 2 индекса 
M[1,1]

Если мы опустим один из индексов, то получим объект пониженной размерности. В случае двумерной матрицы, получим вектор. 

In [ ]:
M

In [ ]:
M[1]

Такой же эффект получится при использовании `:` на месте индекса:

In [ ]:
M[1,:] # строка (row) 1

In [ ]:
M[:,1] # столбец (column) 1

Мы можем присваивать новые значения элементам массива с помощью индексации:

In [ ]:
M[0,0] = 1

In [ ]:
M

In [ ]:
# также работает для строк и столбцов
M[1,:] = 0
M[:,2] = -1

In [ ]:
M

### Срезы (*slice*) по индексам

Срезы по индексам техническое название `M[нижний индекс:верхний индекс:шаг]` предназначенные для извлечения части массива:

In [ ]:
A = array([1,2,3,4,5])
A

In [ ]:
A[1:3]

Срезы массива являются *изменяемыми (mutable)*: если им присвоено новое значение, то исходный массив, из которого был извлечен срез, изменяется:

In [ ]:
A[1:3] = [-2,-3]

A

Можно не указывать любой из трех параметров среза`M[нижний индекс:верхний индекс:шаг]`:

In [ ]:
A[::] # нижний, верхний индексы и шаг (=1) принимают значения по умолчанию

In [ ]:
A[::2] # шаг равен 2, нижний и верхний индексы принимают значения начала и конца массива

In [ ]:
A[:3] # первые три элемента

In [ ]:
A[3:] # элементы с индекса 3

Отрицательные индексы отсчитываются с конца массива (положительные - с начала):

In [ ]:
A = array([1,2,3,4,5])

In [ ]:
A[-1] # последний элемент массива

In [ ]:
A[-3:] # последние 3 элемента

Индексный срез работает точно так же для многомерных массивов:

In [ ]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])

A

In [ ]:
# часть массива
A[1:4, 1:4]

In [ ]:
# пошаговое извлечение
A[::2, ::2]

### Задание 4
Используя срезы извлеките нечетные элементы матрицы А. 

In [ ]:
A[::2,::2]

### Необычное индексирование

О необычном индексировании говорят, когда массив или список используется в качестве индекса: 

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

In [ ]:
col_indices = [1, 2, -1] # вспомним, что -1 это последний элемент
A[:,col_indices]

Можно также использовать индексные маски: Если индексная маска представляет собой массив Numpy типа данных `bool`, то элемент выбирается (True) или нет (False) в зависимости от значения индексной маски в позиции каждого элемента:

In [ ]:
B = array([n for n in range(5)])
B

In [ ]:
row_mask = array([True, False, True, False, False])
B[row_mask]

In [ ]:
# тот же результат
row_mask = array([1,0,1,0,0], dtype=bool)
B[row_mask]

Эта функция очень полезна для условного выбора элементов из массива, используя, например, операторы сравнения:

In [ ]:
x = arange(0, 10, 0.5)
x

In [ ]:
mask = (5 < x) * (x < 7.5)

mask

In [ ]:
x[mask]

### Задание 5
Используйте массив из задания 1 (таблицу умножения) извлеките из него при помощи маски все числа кратные 3. 

In [ ]:
umnoz

In [ ]:
umnoz_cut3 = umnoz[umnoz[:,:] % 3 == 0]

umnoz_cut3

## Функции для извлечения данных из массивов и создания массивов

### Функция where

Индексную маску можно превратить в список индексов, используя `where`:

In [ ]:
indices = where(mask)

indices

In [ ]:
x[indices] # действие этого списка эквивалентно маске, т.е. x[mask]

### Функция diag

При помощи функции diag можно извлекать диагональные элементы с главной и смещенных диагоналей:

In [ ]:
diag(A)

In [ ]:
diag(A, -1)

### Функция take

Функция `take` подобна описанной выше необычной индексации:

In [ ]:
v2 = arange(-3,3)
v2

In [ ]:
row_indices = [1, 3, 5]
v2[row_indices] # необычная индексация

In [ ]:
v2.take(row_indices)

Но функция `take` так же работает на списках и других объектах:

In [ ]:
take([-3, -2, -1,  0,  1,  2], row_indices)

### Функция choose

Создает массив собирая элементы из нескольких массивов:

In [ ]:
which = [1, 0, 1, 0]
choices = [[-1,-2,-3,-4], [6,5,4,3]]

choose(which, choices, mode = 'clip')

In [ ]:
?choose

### Задание 7
Разбить массив таблицы умножения из задания 1 на два массива содержащие четные и нечетные значения, а затем собрать его в исходное состояние используя choose()

In [18]:
matr_odd = umnoz[umnoz[:,:] % 2 == 1]
matr_odd

array([ 1,  3,  5,  7,  9,  3,  9, 15, 21, 27,  5, 15, 25, 35, 45,  7, 21,
       35, 49, 63,  9, 27, 45, 63, 81])

In [19]:
matr_even = umnoz[umnoz[:,:] % 2 == 0]
matr_even

array([  2,   4,   6,   8,  10,   2,   4,   6,   8,  10,  12,  14,  16,
        18,  20,   6,  12,  18,  24,  30,   4,   8,  12,  16,  20,  24,
        28,  32,  36,  40,  10,  20,  30,  40,  50,   6,  12,  18,  24,
        30,  36,  42,  48,  54,  60,  14,  28,  42,  56,  70,   8,  16,
        24,  32,  40,  48,  56,  64,  72,  80,  18,  36,  54,  72,  90,
        10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
def custom_choose(a, b, choose):
  i = 0
  j = 0
  c = linspace(0, 0, 100, dtype = int)
  for cur in choose:
    if cur == 0:
      c[i + j] = a[i]
      i += 1
    else:
      c[i + j] = b[j]
      j += 1
  return c

In [21]:
choices = linspace(0, 0, 100, dtype = int).reshape(10, 10)
choices[1::2,::] = 1
choices[::2,1::2] = 1

choices


array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
choices.reshape(100)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
choices = choices.reshape(100)
custom_choose(matr_odd, matr_even, choices).reshape(10, 10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Линейная алгебра

Векторизация кода-это ключ к написанию эффективных численных вычислений с помощью Python / Numpy. Это означает, что максимально возможная часть программы должна быть сформулирована в терминах матричных и векторных операций, таких как матричного умножения.

### Операции между числами и векторами

Мы можем использовать обычные арифметические операторы для умножения, сложения, вычитания и деления массивов со скалярами или обычными числами.

In [ ]:
v1 = arange(0, 5)

In [ ]:
v1 * 2

In [ ]:
v1 + 2

In [ ]:
A * 2, A + 2

### Поэлементные операции между массивами

Когда мы складываем, вычитаем, умножаем и делим массивы друг с другом, поведение по умолчанию-это операции **по элементам**, т.е. между элементами с совпадающими индексами:

In [ ]:
A * A # поэлементное умножение

In [ ]:
v1 * v1

Если мы умножим массивы с совместимыми размерами, то получим элементарное умножение каждой строки:

In [ ]:
A.shape, v1.shape

In [ ]:
A * v1

### Алгебра матриц

А как насчет умножения матриц? Есть два пути. Мы можем либо использовать функцию `dot`, которая применяет умножение матрица-матрица, матрица-вектор или скалярное векторное к своим двум аргументам:

In [ ]:
dot(A, A)

In [ ]:
dot(A, v1)

In [ ]:
dot(v1, v1)

В качестве альтернативы мы можем привести объекты типа массива к типу `matrix`. Это изменяет поведение стандартных арифметических операторов `+, -, *` для использования алгебры матриц.

In [ ]:
M = matrix(A)
v = matrix(v1).T # транспонирует массив в вектор столбец

In [ ]:
v

In [ ]:
M * M

In [ ]:
M * v

In [ ]:
# скалярное произведение
v.T * v

In [ ]:
# с объектами типа matrix работают все операции
v + M*v

Если использовать операции `+, -, *` с несовместимыми объектами будет выброс исключения или ошибки

In [ ]:
v = matrix([1,2,3,4,5]).T

In [ ]:
shape(M), shape(v)

In [ ]:
M * v

Посмотрите также другие подобные функции: `inner`, `outer`, `cross`, `kron`, `tensordot`. Попробуйте набрать `help(kron)`.

### Преобразования массив/матрица

Выше мы уже использовали `.T` для транспонирования матричного объекта `v`. Мы также могли бы использовать функцию `transpose` для выполнения того же самого.

Другими математическими функциями, преобразующими матричные объекты, являются:

In [ ]:
C = matrix([[1j, 2j], [3j, 4j]])
C

In [ ]:
conjugate(C)

Эрмитово сопряжение: `transpose + conjugate`

In [ ]:
C.H

Можно извлекать действительную и мнимую часть комплексного объекта, используя `real` и `imag`:

In [15]:
real(C) # то же, что и: C.real

NameError: ignored

In [ ]:
imag(C) # то же, что и: C.imag

Или комплексный аргумент(угол) и модуль

In [ ]:
angle(C+1) # для пользователей MATLAB, angle используется вместо arg

In [ ]:
abs(C)

### Задание 8
Даны вектора v1(0,1,2,3,4) v2(5,6,7,8,9) найти угол между ними, учитывая что косинус угла между векторами можно найти как отношения их скалярного произведения к их длинам.

In [ ]:
v1 = array([0, 1, 2, 3, 4])
v2 = array([5, 6, 7, 8, 9])

cos_a = v1 @ v2.T / (sqrt((v1 @ v1.T) * (v2 @ v2.T)))

arccos(cos_a)

In [ ]:
?arccos

### Вычисления над матрицами

#### Функция Inv - инверсия

In [ ]:
linalg.inv(C) # эквивалентно C.I 

In [ ]:
C.I * C

#### Функция det - детерминант

In [ ]:
linalg.det(C)

In [ ]:
linalg.det(C.I)

### Задача 9
Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержающую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы. Если для матрицы не у дается найти обратную, видимо этому мешает нулевое значение детерминанта.

In [ ]:
matr1 = linspace(0, 0, 25, dtype = int).reshape(5,5)
matr2 = copy(matr1)

matr1[::2, ::2] = 5
matr1[1::2, 1::2] = 5
#matr2 = diag([5, 5, 5, 5, 5])
matr2 = triu(linspace(5, 5, 5, dtype = int))

print(matr1)
print(matr2)

In [ ]:
det1 = linalg.det(matr1)
det2 = linalg.det(matr2)
det1, det2

In [ ]:
linalg.inv(matr1)

In [ ]:
linalg.inv(matr2)

### Обработка данных

Часто бывает полезно хранить наборы данных в массивах Numpy. Numpy предоставляет ряд функций для вычисления статистики наборов данных в массивах.

Например, давайте рассчитаем некоторые свойства из набора данных температуры Стокгольма, использованного выше.

In [ ]:
# напоминаем в переменной data храняться данные температуры в Стокгольме
data.shape

#### Функция mean

In [ ]:
# the temperature data is in column 3
mean(data[:,3])

Средняя дневная температура в Стокгольме за последние 200 лет 6.2 C.

#### Функции стандартного отклонения и дисперсии

In [ ]:
std(data[:,3]), var(data[:,3])

#### Функции min и max

In [ ]:
# минимальная температура
data[:,3].min()

In [ ]:
# максимальная температура
data[:,3].max()

#### Функции sum, prod и trace

In [ ]:
d = arange(0, 10)
d

In [ ]:
# сумма всех элементов
sum(d)

In [ ]:
# произведение всех элементов
prod(d+1)

In [ ]:
# совокупная сумма
cumsum(d)

In [ ]:
# совокупное произведение
cumprod(d+1)

In [ ]:
# тоже что и: diag(A).sum()
trace(A)

### Вычисления на подмножествах массива

Можно выполнять вычисления на подмножествах используя индексирование, необычное индексирование и другие методы извлечения данных из массива.

Рассмотрим данные массива температур в Стокгольме:

Формат данных: год, месяц, день, дневная средняя температура, самая низкая, самая высокая, местность.

Если необходимо извлечь среднюю температуру в какой-то конкретный месяц, например февраль, тогда нужно создать маску индексов и использовать ее для извлечения данных только за этот месяц:

In [ ]:
unique(data[:,1]) # столбик месяцев от 1 до 12

In [ ]:
mask_feb = data[:,1] == 2

In [ ]:
# температурные данные в столбике 3
mean(data[mask_feb,3])

С этими интструментами открываются широкие возможности для обработки данных. Например, чтобы извлечь среднюю температуру за месяц по всем месяцам достаточно несколько строк кода:

In [ ]:
months = arange(1,13)
monthly_mean = [mean(data[data[:,1] == month, 3]) for month in months]

fig, ax = plt.subplots()
ax.bar(months, monthly_mean)
ax.set_xlabel("Month")
ax.set_ylabel("Monthly avg. temp.");

### Вычисления с данными высокой размерности

Когда функции, такие как `min`, `max` и т. д. применяются к многомерным массивам, иногда полезно применять расчет ко всему массиву, а иногда только на основе строки или столбца. Используя аргумент `axis`, мы можем указать, как должны вести себя эти функции:

In [ ]:
m = random.rand(3,3)
m

In [ ]:
# максимум по массиву
m.max()

In [ ]:
# максимумы по каждому столбцу
m.max(axis=0)

In [ ]:
# максимумы по каждой строке
m.max(axis=1)

Многие другие функции и методы в классах `array` и `matrix` принимают один и тот же (необязательный) аргумент ключевого слова `axis`.

## Преобразования формы, размера и соединение массивов

Форма массива Numpy может быть изменена без копирования базовых данных, что делает его быстрой операцией даже для больших массивов.

In [ ]:
A

In [ ]:
n, m = A.shape

In [ ]:
B = A.reshape((1,n*m))
B

In [ ]:
B[0,0:5] = 5 # изменим массив

B

In [ ]:
A # и оригинальные данные тоже изменятся. A и B это ссылки на одни и теже данные

Мы также можем использовать функцию `flatten`, чтобы превратить массив более высоких измерений в вектор. Но эта функция создает копию данных.

In [ ]:
B = A.flatten()

B

In [ ]:
B[0:5] = 10

B

In [ ]:
A # теперь A неизменилась, поскольку данные B это копия A, теперь B не ссылается на те же данные.

## Дополнение новых размерностей: newaxis

С `newaxis`, можно добавить новые размерности в массив. Например, превратить вектор в матрицу:

In [ ]:
v = array([1,2,3])

In [ ]:
shape(v)

In [ ]:
# создание столбца матрицы из вектора v
v[:, newaxis]

In [ ]:
# столбец матрицы
v[:,newaxis].shape

In [ ]:
# строка матрицы
v[newaxis,:].shape

## Соединение и повторение массивов

Используя функции `repeat`, `tile`, `vstack`, `hstack` и `concatenate` мы можем создать больше векторов и матриц из более мелких:

### `tile` и `repeat`

In [ ]:
a = array([[1, 2], [3, 4]])

In [ ]:
# повторить каждый элемент 3 раза
repeat(a, 3)

In [ ]:
# повторить матрицу 3 раза 
tile(a, 3)

### `concatenate`

In [ ]:
b = array([[5, 6]])

In [ ]:
concatenate((a, b), axis=0)

In [ ]:
concatenate((a, b.T), axis=1)

### `hstack` и `vstack`

In [ ]:
vstack((a,b))

In [ ]:
hstack((a,b.T))

## Копия и "глубокая копия"

Для достижения высокой производительности назначения в Python обычно не копируют базовые объекты. Это важно, например, когда объекты передаются между функциями, чтобы избежать чрезмерного объема копирования памяти, когда это не является необходимым (технический термин: пропуск по ссылке).

In [ ]:
A = array([[1, 2], [3, 4]])

A

In [ ]:
# теперь В ссылается натеже данные, что и А 
B = A 

In [ ]:
# изменения B отражаются в A
B[0,0] = 10

B

In [ ]:
A

Если мы хотим избежать такого поведения, чтобы при получении нового полностью независимого объекта `B`, скопированного из `A`, нам нужно было сделать так называемое "глубокое копирование" с помощью функции `copy`:

In [ ]:
B = copy(A)

In [ ]:
# теперь при изменении В, А не меняется

B

In [ ]:
A

## Иттерация на элементах массива

Как правило, мы хотим избежать повторения элементов массивов всякий раз, когда это возможно (любой ценой). Причина в том, что в интерпретируемом языке, таком как Python (или MATLAB), итерации действительно медленны по сравнению с векторизованными операциями.

Однако, иногда итерации неизбежны. Для таких случаев цикл Python `for` является наиболее удобным способом перебора массива:

In [ ]:
v = array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

Когда нам нужно перебирать каждый элемент массива и изменять его элементы, удобно использовать функцию `enumerate` для получения как элемента, так и его индекса в цикле `for` :

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # обновляет матрицу M: возводя ее элементы в квадрат
        M[row_idx, col_idx] = element ** 2

In [ ]:
# каждый элемент в M возведен в квадрат
M

## Векторные функции

Как уже упоминалось несколько раз, чтобы получить хорошую производительность, мы должны стараться избегать циклического перебора элементов в наших векторах и матрицах, а вместо этого использовать векторизованные алгоритмы. Первый шаг в преобразовании скалярного алгоритма в векторизованный алгоритм заключается в том, чтобы убедиться, что функции, которые мы пишем, работают с векторными входными данными.

In [ ]:
def Theta(x):
    """
    Скалярная реализация функции порога Хевисайда.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
Theta(array([-3,-2,-1,0,1,2,3]))

Хорошо, это не сработало, потому что мы не написали функцию `Theta`, чтобы она могла обрабатывать векторный ввод...

Чтобы получить векторизованную версию теты, мы можем использовать функцию Numpy `vectorize`. Во многих случаях он может автоматически векторизовать функцию:

In [ ]:
Theta_vec = vectorize(Theta)

In [ ]:
Theta_vec(array([-3,-2,-1,0,1,2,3]))

Мы также можем реализовать функцию для приема векторного ввода с самого начала (требует больше усилий, но может дать лучшую производительность):

In [ ]:
def Theta(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [ ]:
Theta(array([-3,-2,-1,0,1,2,3]))

In [ ]:
# still works for scalars as well
Theta(-1.2), Theta(2.6)

## Использование массива в условии

При использовании массивов в условиях, например, `if` операторы и другие логические выражения, нужно использовать `any` или `all`, что требует, чтобы любой или все элементы в массиве равнялись `True`:

In [ ]:
M

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

## Подбор типа

Поскольку массивы Numpy статически типизированы, тип массива не изменяется после его создания. Но мы можем явно привести массив некоторого типа к другому, используя функции `astype` (см. также аналогичную функцию `asarray`). Это всегда создает новый массив нового типа:

In [ ]:
M.dtype

In [ ]:
M2 = M.astype(float)

M2

In [ ]:
M2.dtype

In [ ]:
M3 = M.astype(bool)

M3

## Дальнейшее изучение

* http://numpy.scipy.org
* [Tentative NumPy Tutorial](http://scipy.org/Tentative_NumPy_Tutorial)
* [A Numpy guide for MATLAB users](http://scipy.org/NumPy_for_Matlab_Users).
* Этот [материал](http://github.com/jrjohansson/scientific-python-lectures) создан на основе книг [J.R. Johansson](http://jrjohansson.github.io).