In [2]:
import numpy as np
import pandas as pd
import scipy.stats as sc
import statsmodels.api as sm

In [46]:
import warnings
warnings.filterwarnings("ignore")

In [8]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Эконометрика/Семинар 10 декабря.csv', sep = ';', decimal = ',')
df.head()

Область      Y     X1     X2     X3
0   1.        Белгородская  15.3  135.2  109.5  125.2
1      2.        Брянская   18.6   86.5  111.4  112.2
2  3.        Владимирская   19.4  107.4  105.3  105.1
3    4.        Воронежская  18.1  108.1  105.1  112.4
4    5.        Ивановская   19.9  104.6  112.0  106.2

#Виф Тест 

In [13]:
model_1 = sm.OLS.from_formula("X1 ~ X2 + X3", data = df)
print(model_1.fit().summary())

                            OLS Regression Results                            
Dep. Variable:                     X1   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     1.028
Date:                Sat, 10 Dec 2022   Prob (F-statistic):              0.382
Time:                        12:44:26   Log-Likelihood:                -73.332
No. Observations:                  18   AIC:                             152.7
Df Residuals:                      15   BIC:                             155.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    241.2959    108.675      2.220      0.0

/usr/local/lib/python3.8/dist-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [14]:
r_2 = 0.121
vif = 1 / (1 - r_2)
vif

1.1376564277588168

In [16]:
model_2 = sm.OLS.from_formula("X2 ~ X1 + X3", data = df)
print(model_2.fit().summary())

                            OLS Regression Results                            
Dep. Variable:                     X2   R-squared:                       0.129
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     1.107
Date:                Sat, 10 Dec 2022   Prob (F-statistic):              0.356
Time:                        12:45:35   Log-Likelihood:                -47.998
No. Observations:                  18   AIC:                             102.0
Df Residuals:                      15   BIC:                             104.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    114.1016      8.493     13.435      0.0

/usr/local/lib/python3.8/dist-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [17]:
r_2 = 0.129
vif = 1 / (1 - r_2)
vif

1.148105625717566

In [18]:
model_3 = sm.OLS.from_formula("X3 ~ X1 + X2", data = df)
print(model_3.fit().summary())

                            OLS Regression Results                            
Dep. Variable:                     X3   R-squared:                       0.034
Model:                            OLS   Adj. R-squared:                 -0.095
Method:                 Least Squares   F-statistic:                    0.2642
Date:                Sat, 10 Dec 2022   Prob (F-statistic):              0.771
Time:                        12:46:05   Log-Likelihood:                -73.771
No. Observations:                  18   AIC:                             153.5
Df Residuals:                      15   BIC:                             156.2
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     14.2163    128.304      0.111      0.9

/usr/local/lib/python3.8/dist-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [19]:
r_2 = 0.034
vif = 1 / (1 - r_2)
vif

1.0351966873706004

Все 3 значения vif-теста < 10 (крит значение) следовательно мультиколлинеарность отсутствует.

Можно приступить к прогнозированию и анализу модели.

In [20]:
model = sm.OLS.from_formula("Y ~ X1 + X2 + X3", data = df)
lin_model_sum = model.fit().summary()
print(lin_model_sum)

                            OLS Regression Results                            
Dep. Variable:                      Y   R-squared:                       0.666
Model:                            OLS   Adj. R-squared:                  0.594
Method:                 Least Squares   F-statistic:                     9.294
Date:                Sat, 10 Dec 2022   Prob (F-statistic):            0.00123
Time:                        12:50:11   Log-Likelihood:                -29.069
No. Observations:                  18   AIC:                             66.14
Df Residuals:                      14   BIC:                             69.70
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     69.5320     11.088      6.271      0.0

/usr/local/lib/python3.8/dist-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


p-value для F-теста и t-теста на значимость модели и параметров модели < 0.05, следовательно модель значима, как и все 3 экзогенных переменных

##Алгоритм Фарара-Глоубера

Включает в себя 3 теста на мультикллинеарность, проверим по очереди каждый из них

####Хи квадрат статистика

In [25]:
corr_matr = df.drop('Y', axis = 1).corr()
det = np.linalg.det(corr_matr.values)
det

0.865116163185151

In [28]:
FG = -(17 - 11/6)*np.log(det)
FG

2.197520906901297

In [31]:
hi_2 = sc.chi2.isf(0.05, 1/2 * 3 * 2)
hi_2

7.814727903251178

hi_2 (табл) > FG, следовательно мультиколлинеарность по данному тесту отсутствует

####F-тест

In [34]:
obr = np.linalg.inv(corr_matr).diagonal()
obr

array([1.1370754 , 1.14761281, 1.03522183])

In [35]:
F_stat = (obr - 1) * (14 / 3)
F_stat

array([0.63968518, 0.6888598 , 0.16436852])

In [37]:
F_tabl = sc.f.ppf(0.95, 3, 14)
F_tabl

3.3438886781189123

F_tabl > F_факт, в рамках F-теста у нас нет связи с другими регрессорами

##t-test

In [48]:
c = np.linalg.inv(corr_matr)
r = np.copy(c)
for i in range(3):
  for j in range(3):
    r[i, j] = -c[i, j] / np.sqrt(c[i, i] * c[j, j])
r

array([[-1.        , -0.33791907,  0.13423649],
       [-0.33791907, -1.        ,  0.16442632],
       [ 0.13423649,  0.16442632, -1.        ]])

In [47]:
c = np.linalg.inv(corr_matr)
t = np.copy(r)
for i in range(3):
  for j in range(3):
    t[i, j] = abs(r[i, j] * np.sqrt(14 / (1 - r[i, j] ** 2)))
t

array([[       inf, 1.34340283, 0.50685434],
       [1.34340283,        inf, 0.62371612],
       [0.50685434, 0.62371612,        inf]])

In [43]:
t_tabl = sc.t.ppf(0.975, 14)
t_tabl

2.1447866879169273

In [44]:
t_tabl > t

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

t-tabl>все попарные значения t-теста для параметров(главная диагональ не рассматривается, следовательно по t-тесту мультиколлинеарность отсутствует