# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [177]:
arr = np.random.uniform(0, 21, size=(4, 7))

arr = (arr - np.min(arr))/(np.max(arr) - np.min(arr))

arr

array([[0.63299653, 0.41321101, 0.04086536, 0.45895207, 0.66431731,
        0.11057954, 0.61895272],
       [0.16198165, 0.91799139, 0.50210157, 0.27382068, 0.19423692,
        0.56072449, 0.58900569],
       [0.51978804, 0.53097304, 0.0144278 , 0.        , 0.81383819,
        0.23506928, 0.24010035],
       [0.58623841, 0.03721053, 0.85383079, 1.        , 0.40365524,
        0.50947087, 0.03389149]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [178]:
matr = np.random.randint(11, size=(8, 10))

ma = matr.sum(axis = 1)

print(matr, '\n')
print(np.argmin(ma), matr[np.argmin(ma)])

[[ 4  3  7 10  5  9  9  1  8  5]
 [ 3  7  7  4  0 10  8  0  2  4]
 [ 1  4 10  3  4  7  4  3  5  0]
 [10  0  7  5  7  7  2  5  0  5]
 [ 4  7  6  5  7  5  1  8  0  7]
 [ 6  0  8  6  1  2  6  7  9 10]
 [ 9  1  0  9  3  5  2  5  8  1]
 [ 4  0  3  8 10  9  0  1  7  7]] 

2 [ 1  4 10  3  4  7  4  3  5  0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [179]:
vect1 = np.array([1, 2, 3])
vect2 = np.array([1, 4, 3])

print(np.sqrt(sum((vect1 - vect2) ** 2)))

2.0


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [180]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = -np.linalg.inv(A) @ C @ np.linalg.inv(B)



## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [181]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)

data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [182]:
var = np.average(data[:, 1:], axis = 0)
max1 = np.max(data[:, 1:], axis = 0)
min1 = np.min(data[:, 1:], axis = 0)
med = np.median(data[:, 1:], axis = 0)

print(var, max1, min1, med, sep = '\n')

[2.16010017e+04 9.05528000e+00]
[2147483647         39]
[0 1]
[40.  9.]


3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [183]:
data[np.random.choice(np.array(range(1, len(data))), 10)]

array([[ 83155,     75,      9],
       [364633,     30,      9],
       [169402,    500,      9],
       [281049,     50,      7],
       [100062,    170,     16],
       [111998,     25,      9],
       [282920,     55,     12],
       [  4344,     15,     11],
       [390290,      5,      4],
       [354743,     45,      7]])

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [184]:
data_cutted = data[data[:,2] <= 5]

data_cutted

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [185]:
kol = np.var(data[:, 2])

len(data[data[:, 2] < kol]) / len(data) * 100

88.292

6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [186]:
q_75 = np.quantile(data[:, 1], 0.75)

print(q_75)


data[data[:, 1] > 65, 1] = q_75
data

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [187]:
print(np.size(data[data[:, 1] == 0]) / 3)

data[data[:, 1] == 0, 1] = 1
data

479.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [188]:
number, quantity = np.unique(data[:,2], return_counts = True)
print(np.asarray(np.c_[number, quantity]))

not_included = np.where(np.isin(np.linspace(1,41, 41, dtype = int), number) == False)[0]
not_included.tolist()

[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


[35, 37, 39, 40]

9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [189]:
example = np.array(data[:,2] / data[:,1]).reshape(int(np.size(data) / 3), 1)
data = np.c_[data, example]

In [192]:
print(data)
print(np.max(data[:, 3]))

[[1.27244000e+05 6.00000000e+01 1.60000000e+01 2.66666667e-01]
 [2.38910000e+04 2.50000000e+01 7.00000000e+00 2.80000000e-01]
 [9.47460000e+04 1.00000000e+01 6.00000000e+00 6.00000000e-01]
 ...
 [4.98432000e+05 6.50000000e+01 1.50000000e+01 2.30769231e-01]
 [3.70915000e+05 5.00000000e+00 4.00000000e+00 8.00000000e-01]
 [8.19930000e+04 6.50000000e+01 1.40000000e+01 2.15384615e-01]]
24.0


10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [196]:
top_100 = data[np.argsort(data[:, 1])]
top_100 = top_100[-1:-101:-1]
#print(top_100)

print(np.average(top_100[:,2]))

9.96


11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [145]:
simple = np.copy(data)
mask = (simple[:,1] <= 20) & (simple[:,2] <= 5)
print(np.array(mask, dtype = int))
simple = np.c_[simple, mask]

[0 0 0 ... 0 1 0]


In [158]:
print(simple)
print(len(simple[simple[:, 4] == 1]) / len(simple) * 100, '%')

[[1.27244000e+05 6.00000000e+01 1.60000000e+01 2.66666667e-01
  0.00000000e+00]
 [2.38910000e+04 2.50000000e+01 7.00000000e+00 2.80000000e-01
  0.00000000e+00]
 [9.47460000e+04 1.00000000e+01 6.00000000e+00 6.00000000e-01
  0.00000000e+00]
 ...
 [4.98432000e+05 6.50000000e+01 1.50000000e+01 2.30769231e-01
  0.00000000e+00]
 [3.70915000e+05 5.00000000e+00 4.00000000e+00 8.00000000e-01
  1.00000000e+00]
 [8.19930000e+04 6.50000000e+01 1.40000000e+01 2.15384615e-01
  0.00000000e+00]]
9.552 %


12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [172]:
time_10 = data[data[:, 1] < 10]
time_10_20 = data[np.where((data[:,1] >= 10) & (data[:,1] <= 20))[0]]
time_20 = data[data[:, 1] > 20]

total_size = np.min([len(time_10), len(time_10_20), len(time_20)])

grouped_data = np.array([time_10[:total_size], time_10_20[:total_size], time_20[:total_size]])
grouped_data

array([[[6.76600000e+04, 5.00000000e+00, 6.00000000e+00, 1.20000000e+00],
        [3.66174000e+05, 7.00000000e+00, 9.00000000e+00, 1.28571429e+00],
        [2.04134000e+05, 5.00000000e+00, 3.00000000e+00, 6.00000000e-01],
        ...,
        [4.20725000e+05, 5.00000000e+00, 3.00000000e+00, 6.00000000e-01],
        [4.74700000e+03, 1.00000000e+00, 9.00000000e+00, 9.00000000e+00],
        [3.70915000e+05, 5.00000000e+00, 4.00000000e+00, 8.00000000e-01]],

       [[9.47460000e+04, 1.00000000e+01, 6.00000000e+00, 6.00000000e-01],
        [3.39410000e+04, 1.80000000e+01, 9.00000000e+00, 5.00000000e-01],
        [4.46597000e+05, 1.50000000e+01, 5.00000000e+00, 3.33333333e-01],
        ...,
        [3.31810000e+05, 1.30000000e+01, 1.20000000e+01, 9.23076923e-01],
        [2.75677000e+05, 1.50000000e+01, 8.00000000e+00, 5.33333333e-01],
        [2.82714000e+05, 1.50000000e+01, 6.00000000e+00, 4.00000000e-01]],

       [[1.27244000e+05, 6.00000000e+01, 1.60000000e+01, 2.66666667e-01],
        

In [173]:
np.shape(grouped_data)

(3, 7588, 4)

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [235]:
example_data_1 = data

cost = 5 * example_data_1[:, 1] + 10 * example_data_1[:, 2]
#print(np.shape(cost))

data_and_price = np.append(example_data_1, cost.reshape(len(cost), 1), axis = 1)


#Это без учёта группировки
print(data_and_price[:10, 4])

[460. 195. 110.  85. 440. 270. 180. 125. 125. 170.]


In [236]:
example_data = grouped_data

cost = 5 * example_data[:, :, 1] + 10 * example_data[:, :, 2]
#print(np.shape(cost))

data_and_price = np.append(example_data, cost.reshape(3, int(np.size(cost) / 3), 1), axis = 2)
#print(data_and_price[0:10])

#Это для случая с 12 задачей
print(np.average(data_and_price[:, :10, 4], axis = 1))

[ 83.5 145.  368. ]


In [1]:
import numpy as np
import pandas